version: "3.9"
services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000
  db:
    build:
      dockerfile: mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: atsuya
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: calculation_app
