version: "3.9"
services:
  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html/src
    command: php -S 0.0.0.0:8000
  db:
    build:
      dockerfile: mysql/Dockerfile
    ports:
      - "3306:3306"
    env_file: mysql/db.env
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql

volumes:
  db-data:
